/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignRouteImport } from './routes/sign'
import { Route as PlayRouteImport } from './routes/play'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AllianceRouteImport } from './routes/alliance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardLeagueRouteImport } from './routes/dashboard/league'
import { Route as DashboardLeaderboardRouteImport } from './routes/dashboard/leaderboard'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardBetsRouteImport } from './routes/dashboard/bets'
import { Route as ApiLeaderboardRouteImport } from './routes/api/leaderboard'
import { Route as ApiUserSubmitQuestVerificationRouteImport } from './routes/api/user.submit-quest-verification'
import { Route as ApiUserRegisterReferralRouteImport } from './routes/api/user.register-referral'
import { Route as ApiUserProfileRouteImport } from './routes/api/user.profile'
import { Route as ApiUserConvertCoinsRouteImport } from './routes/api/user.convert-coins'
import { Route as ApiUserClaimWinningsRouteImport } from './routes/api/user.claim-winnings'
import { Route as ApiUserClaimWelcomeGiftRouteImport } from './routes/api/user.claim-welcome-gift'
import { Route as ApiUserClaimSocialRewardRouteImport } from './routes/api/user.claim-social-reward'
import { Route as ApiUserClaimAllianceRewardsRouteImport } from './routes/api/user.claim-alliance-rewards'
import { Route as ApiUserCheckInRouteImport } from './routes/api/user.check-in'
import { Route as ApiMinigameBetAccumulatorRouteImport } from './routes/api/minigame.bet-accumulator'
import { Route as ApiMinigameBetRouteImport } from './routes/api/minigame.bet'
import { Route as ApiMatchesUpdateResultRouteImport } from './routes/api/matches.update-result'
import { Route as ApiMatchesCurrentRouteImport } from './routes/api/matches.current'
import { Route as ApiMatchesCreateRouteImport } from './routes/api/matches.create'
import { Route as ApiLeaguesStandingsRouteImport } from './routes/api/leagues.standings'
import { Route as ApiGameResetRouteImport } from './routes/api/game.reset'
import { Route as ApiCouponsVerifyRouteImport } from './routes/api/coupons.verify'
import { Route as ApiBetsSettleRouteImport } from './routes/api/bets.settle'
import { Route as ApiBetsActiveRouteImport } from './routes/api/bets.active'
import { Route as ApiAdminVerifyRouteImport } from './routes/api/admin.verify'
import { Route as ApiAdminValidateSessionRouteImport } from './routes/api/admin.validate-session'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin.logout'
import { Route as ApiAdminConfigRouteImport } from './routes/api/admin.config'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AllianceRoute = AllianceRouteImport.update({
  id: '/alliance',
  path: '/alliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeagueRoute = DashboardLeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeaderboardRoute = DashboardLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBetsRoute = DashboardBetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSubmitQuestVerificationRoute =
  ApiUserSubmitQuestVerificationRouteImport.update({
    id: '/api/user/submit-quest-verification',
    path: '/api/user/submit-quest-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUserRegisterReferralRoute = ApiUserRegisterReferralRouteImport.update({
  id: '/api/user/register-referral',
  path: '/api/user/register-referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: '/api/user/profile',
  path: '/api/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserConvertCoinsRoute = ApiUserConvertCoinsRouteImport.update({
  id: '/api/user/convert-coins',
  path: '/api/user/convert-coins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserClaimWinningsRoute = ApiUserClaimWinningsRouteImport.update({
  id: '/api/user/claim-winnings',
  path: '/api/user/claim-winnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserClaimWelcomeGiftRoute = ApiUserClaimWelcomeGiftRouteImport.update({
  id: '/api/user/claim-welcome-gift',
  path: '/api/user/claim-welcome-gift',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserClaimSocialRewardRoute =
  ApiUserClaimSocialRewardRouteImport.update({
    id: '/api/user/claim-social-reward',
    path: '/api/user/claim-social-reward',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUserClaimAllianceRewardsRoute =
  ApiUserClaimAllianceRewardsRouteImport.update({
    id: '/api/user/claim-alliance-rewards',
    path: '/api/user/claim-alliance-rewards',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUserCheckInRoute = ApiUserCheckInRouteImport.update({
  id: '/api/user/check-in',
  path: '/api/user/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMinigameBetAccumulatorRoute =
  ApiMinigameBetAccumulatorRouteImport.update({
    id: '/api/minigame/bet-accumulator',
    path: '/api/minigame/bet-accumulator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMinigameBetRoute = ApiMinigameBetRouteImport.update({
  id: '/api/minigame/bet',
  path: '/api/minigame/bet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesUpdateResultRoute = ApiMatchesUpdateResultRouteImport.update({
  id: '/api/matches/update-result',
  path: '/api/matches/update-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesCurrentRoute = ApiMatchesCurrentRouteImport.update({
  id: '/api/matches/current',
  path: '/api/matches/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesCreateRoute = ApiMatchesCreateRouteImport.update({
  id: '/api/matches/create',
  path: '/api/matches/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaguesStandingsRoute = ApiLeaguesStandingsRouteImport.update({
  id: '/api/leagues/standings',
  path: '/api/leagues/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameResetRoute = ApiGameResetRouteImport.update({
  id: '/api/game/reset',
  path: '/api/game/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCouponsVerifyRoute = ApiCouponsVerifyRouteImport.update({
  id: '/api/coupons/verify',
  path: '/api/coupons/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetsSettleRoute = ApiBetsSettleRouteImport.update({
  id: '/api/bets/settle',
  path: '/api/bets/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetsActiveRoute = ApiBetsActiveRouteImport.update({
  id: '/api/bets/active',
  path: '/api/bets/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVerifyRoute = ApiAdminVerifyRouteImport.update({
  id: '/api/admin/verify',
  path: '/api/admin/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminValidateSessionRoute = ApiAdminValidateSessionRouteImport.update({
  id: '/api/admin/validate-session',
  path: '/api/admin/validate-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConfigRoute = ApiAdminConfigRouteImport.update({
  id: '/api/admin/config',
  path: '/api/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alliance': typeof AllianceRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/entry': typeof EntryRoute
  '/onboarding': typeof OnboardingRoute
  '/play': typeof PlayRoute
  '/sign': typeof SignRoute
  '/welcome': typeof WelcomeRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/dashboard/bets': typeof DashboardBetsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/league': typeof DashboardLeagueRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/validate-session': typeof ApiAdminValidateSessionRoute
  '/api/admin/verify': typeof ApiAdminVerifyRoute
  '/api/bets/active': typeof ApiBetsActiveRoute
  '/api/bets/settle': typeof ApiBetsSettleRoute
  '/api/coupons/verify': typeof ApiCouponsVerifyRoute
  '/api/game/reset': typeof ApiGameResetRoute
  '/api/leagues/standings': typeof ApiLeaguesStandingsRoute
  '/api/matches/create': typeof ApiMatchesCreateRoute
  '/api/matches/current': typeof ApiMatchesCurrentRoute
  '/api/matches/update-result': typeof ApiMatchesUpdateResultRoute
  '/api/minigame/bet': typeof ApiMinigameBetRoute
  '/api/minigame/bet-accumulator': typeof ApiMinigameBetAccumulatorRoute
  '/api/user/check-in': typeof ApiUserCheckInRoute
  '/api/user/claim-alliance-rewards': typeof ApiUserClaimAllianceRewardsRoute
  '/api/user/claim-social-reward': typeof ApiUserClaimSocialRewardRoute
  '/api/user/claim-welcome-gift': typeof ApiUserClaimWelcomeGiftRoute
  '/api/user/claim-winnings': typeof ApiUserClaimWinningsRoute
  '/api/user/convert-coins': typeof ApiUserConvertCoinsRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/register-referral': typeof ApiUserRegisterReferralRoute
  '/api/user/submit-quest-verification': typeof ApiUserSubmitQuestVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alliance': typeof AllianceRoute
  '/connect': typeof ConnectRoute
  '/entry': typeof EntryRoute
  '/onboarding': typeof OnboardingRoute
  '/play': typeof PlayRoute
  '/sign': typeof SignRoute
  '/welcome': typeof WelcomeRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/dashboard/bets': typeof DashboardBetsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/league': typeof DashboardLeagueRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/validate-session': typeof ApiAdminValidateSessionRoute
  '/api/admin/verify': typeof ApiAdminVerifyRoute
  '/api/bets/active': typeof ApiBetsActiveRoute
  '/api/bets/settle': typeof ApiBetsSettleRoute
  '/api/coupons/verify': typeof ApiCouponsVerifyRoute
  '/api/game/reset': typeof ApiGameResetRoute
  '/api/leagues/standings': typeof ApiLeaguesStandingsRoute
  '/api/matches/create': typeof ApiMatchesCreateRoute
  '/api/matches/current': typeof ApiMatchesCurrentRoute
  '/api/matches/update-result': typeof ApiMatchesUpdateResultRoute
  '/api/minigame/bet': typeof ApiMinigameBetRoute
  '/api/minigame/bet-accumulator': typeof ApiMinigameBetAccumulatorRoute
  '/api/user/check-in': typeof ApiUserCheckInRoute
  '/api/user/claim-alliance-rewards': typeof ApiUserClaimAllianceRewardsRoute
  '/api/user/claim-social-reward': typeof ApiUserClaimSocialRewardRoute
  '/api/user/claim-welcome-gift': typeof ApiUserClaimWelcomeGiftRoute
  '/api/user/claim-winnings': typeof ApiUserClaimWinningsRoute
  '/api/user/convert-coins': typeof ApiUserConvertCoinsRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/register-referral': typeof ApiUserRegisterReferralRoute
  '/api/user/submit-quest-verification': typeof ApiUserSubmitQuestVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alliance': typeof AllianceRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/entry': typeof EntryRoute
  '/onboarding': typeof OnboardingRoute
  '/play': typeof PlayRoute
  '/sign': typeof SignRoute
  '/welcome': typeof WelcomeRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/dashboard/bets': typeof DashboardBetsRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/league': typeof DashboardLeagueRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/validate-session': typeof ApiAdminValidateSessionRoute
  '/api/admin/verify': typeof ApiAdminVerifyRoute
  '/api/bets/active': typeof ApiBetsActiveRoute
  '/api/bets/settle': typeof ApiBetsSettleRoute
  '/api/coupons/verify': typeof ApiCouponsVerifyRoute
  '/api/game/reset': typeof ApiGameResetRoute
  '/api/leagues/standings': typeof ApiLeaguesStandingsRoute
  '/api/matches/create': typeof ApiMatchesCreateRoute
  '/api/matches/current': typeof ApiMatchesCurrentRoute
  '/api/matches/update-result': typeof ApiMatchesUpdateResultRoute
  '/api/minigame/bet': typeof ApiMinigameBetRoute
  '/api/minigame/bet-accumulator': typeof ApiMinigameBetAccumulatorRoute
  '/api/user/check-in': typeof ApiUserCheckInRoute
  '/api/user/claim-alliance-rewards': typeof ApiUserClaimAllianceRewardsRoute
  '/api/user/claim-social-reward': typeof ApiUserClaimSocialRewardRoute
  '/api/user/claim-welcome-gift': typeof ApiUserClaimWelcomeGiftRoute
  '/api/user/claim-winnings': typeof ApiUserClaimWinningsRoute
  '/api/user/convert-coins': typeof ApiUserConvertCoinsRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/register-referral': typeof ApiUserRegisterReferralRoute
  '/api/user/submit-quest-verification': typeof ApiUserSubmitQuestVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alliance'
    | '/connect'
    | '/dashboard'
    | '/entry'
    | '/onboarding'
    | '/play'
    | '/sign'
    | '/welcome'
    | '/api/leaderboard'
    | '/dashboard/bets'
    | '/dashboard/home'
    | '/dashboard/leaderboard'
    | '/dashboard/league'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/admin/config'
    | '/api/admin/logout'
    | '/api/admin/validate-session'
    | '/api/admin/verify'
    | '/api/bets/active'
    | '/api/bets/settle'
    | '/api/coupons/verify'
    | '/api/game/reset'
    | '/api/leagues/standings'
    | '/api/matches/create'
    | '/api/matches/current'
    | '/api/matches/update-result'
    | '/api/minigame/bet'
    | '/api/minigame/bet-accumulator'
    | '/api/user/check-in'
    | '/api/user/claim-alliance-rewards'
    | '/api/user/claim-social-reward'
    | '/api/user/claim-welcome-gift'
    | '/api/user/claim-winnings'
    | '/api/user/convert-coins'
    | '/api/user/profile'
    | '/api/user/register-referral'
    | '/api/user/submit-quest-verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alliance'
    | '/connect'
    | '/entry'
    | '/onboarding'
    | '/play'
    | '/sign'
    | '/welcome'
    | '/api/leaderboard'
    | '/dashboard/bets'
    | '/dashboard/home'
    | '/dashboard/leaderboard'
    | '/dashboard/league'
    | '/dashboard/profile'
    | '/dashboard'
    | '/api/admin/config'
    | '/api/admin/logout'
    | '/api/admin/validate-session'
    | '/api/admin/verify'
    | '/api/bets/active'
    | '/api/bets/settle'
    | '/api/coupons/verify'
    | '/api/game/reset'
    | '/api/leagues/standings'
    | '/api/matches/create'
    | '/api/matches/current'
    | '/api/matches/update-result'
    | '/api/minigame/bet'
    | '/api/minigame/bet-accumulator'
    | '/api/user/check-in'
    | '/api/user/claim-alliance-rewards'
    | '/api/user/claim-social-reward'
    | '/api/user/claim-welcome-gift'
    | '/api/user/claim-winnings'
    | '/api/user/convert-coins'
    | '/api/user/profile'
    | '/api/user/register-referral'
    | '/api/user/submit-quest-verification'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alliance'
    | '/connect'
    | '/dashboard'
    | '/entry'
    | '/onboarding'
    | '/play'
    | '/sign'
    | '/welcome'
    | '/api/leaderboard'
    | '/dashboard/bets'
    | '/dashboard/home'
    | '/dashboard/leaderboard'
    | '/dashboard/league'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/admin/config'
    | '/api/admin/logout'
    | '/api/admin/validate-session'
    | '/api/admin/verify'
    | '/api/bets/active'
    | '/api/bets/settle'
    | '/api/coupons/verify'
    | '/api/game/reset'
    | '/api/leagues/standings'
    | '/api/matches/create'
    | '/api/matches/current'
    | '/api/matches/update-result'
    | '/api/minigame/bet'
    | '/api/minigame/bet-accumulator'
    | '/api/user/check-in'
    | '/api/user/claim-alliance-rewards'
    | '/api/user/claim-social-reward'
    | '/api/user/claim-welcome-gift'
    | '/api/user/claim-winnings'
    | '/api/user/convert-coins'
    | '/api/user/profile'
    | '/api/user/register-referral'
    | '/api/user/submit-quest-verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AllianceRoute: typeof AllianceRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EntryRoute: typeof EntryRoute
  OnboardingRoute: typeof OnboardingRoute
  PlayRoute: typeof PlayRoute
  SignRoute: typeof SignRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiLeaderboardRoute: typeof ApiLeaderboardRoute
  ApiAdminConfigRoute: typeof ApiAdminConfigRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminValidateSessionRoute: typeof ApiAdminValidateSessionRoute
  ApiAdminVerifyRoute: typeof ApiAdminVerifyRoute
  ApiBetsActiveRoute: typeof ApiBetsActiveRoute
  ApiBetsSettleRoute: typeof ApiBetsSettleRoute
  ApiCouponsVerifyRoute: typeof ApiCouponsVerifyRoute
  ApiGameResetRoute: typeof ApiGameResetRoute
  ApiLeaguesStandingsRoute: typeof ApiLeaguesStandingsRoute
  ApiMatchesCreateRoute: typeof ApiMatchesCreateRoute
  ApiMatchesCurrentRoute: typeof ApiMatchesCurrentRoute
  ApiMatchesUpdateResultRoute: typeof ApiMatchesUpdateResultRoute
  ApiMinigameBetRoute: typeof ApiMinigameBetRoute
  ApiMinigameBetAccumulatorRoute: typeof ApiMinigameBetAccumulatorRoute
  ApiUserCheckInRoute: typeof ApiUserCheckInRoute
  ApiUserClaimAllianceRewardsRoute: typeof ApiUserClaimAllianceRewardsRoute
  ApiUserClaimSocialRewardRoute: typeof ApiUserClaimSocialRewardRoute
  ApiUserClaimWelcomeGiftRoute: typeof ApiUserClaimWelcomeGiftRoute
  ApiUserClaimWinningsRoute: typeof ApiUserClaimWinningsRoute
  ApiUserConvertCoinsRoute: typeof ApiUserConvertCoinsRoute
  ApiUserProfileRoute: typeof ApiUserProfileRoute
  ApiUserRegisterReferralRoute: typeof ApiUserRegisterReferralRoute
  ApiUserSubmitQuestVerificationRoute: typeof ApiUserSubmitQuestVerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alliance': {
      id: '/alliance'
      path: '/alliance'
      fullPath: '/alliance'
      preLoaderRoute: typeof AllianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/league': {
      id: '/dashboard/league'
      path: '/league'
      fullPath: '/dashboard/league'
      preLoaderRoute: typeof DashboardLeagueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leaderboard': {
      id: '/dashboard/leaderboard'
      path: '/leaderboard'
      fullPath: '/dashboard/leaderboard'
      preLoaderRoute: typeof DashboardLeaderboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bets': {
      id: '/dashboard/bets'
      path: '/bets'
      fullPath: '/dashboard/bets'
      preLoaderRoute: typeof DashboardBetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/submit-quest-verification': {
      id: '/api/user/submit-quest-verification'
      path: '/api/user/submit-quest-verification'
      fullPath: '/api/user/submit-quest-verification'
      preLoaderRoute: typeof ApiUserSubmitQuestVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/register-referral': {
      id: '/api/user/register-referral'
      path: '/api/user/register-referral'
      fullPath: '/api/user/register-referral'
      preLoaderRoute: typeof ApiUserRegisterReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/profile': {
      id: '/api/user/profile'
      path: '/api/user/profile'
      fullPath: '/api/user/profile'
      preLoaderRoute: typeof ApiUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/convert-coins': {
      id: '/api/user/convert-coins'
      path: '/api/user/convert-coins'
      fullPath: '/api/user/convert-coins'
      preLoaderRoute: typeof ApiUserConvertCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/claim-winnings': {
      id: '/api/user/claim-winnings'
      path: '/api/user/claim-winnings'
      fullPath: '/api/user/claim-winnings'
      preLoaderRoute: typeof ApiUserClaimWinningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/claim-welcome-gift': {
      id: '/api/user/claim-welcome-gift'
      path: '/api/user/claim-welcome-gift'
      fullPath: '/api/user/claim-welcome-gift'
      preLoaderRoute: typeof ApiUserClaimWelcomeGiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/claim-social-reward': {
      id: '/api/user/claim-social-reward'
      path: '/api/user/claim-social-reward'
      fullPath: '/api/user/claim-social-reward'
      preLoaderRoute: typeof ApiUserClaimSocialRewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/claim-alliance-rewards': {
      id: '/api/user/claim-alliance-rewards'
      path: '/api/user/claim-alliance-rewards'
      fullPath: '/api/user/claim-alliance-rewards'
      preLoaderRoute: typeof ApiUserClaimAllianceRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/check-in': {
      id: '/api/user/check-in'
      path: '/api/user/check-in'
      fullPath: '/api/user/check-in'
      preLoaderRoute: typeof ApiUserCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/minigame/bet-accumulator': {
      id: '/api/minigame/bet-accumulator'
      path: '/api/minigame/bet-accumulator'
      fullPath: '/api/minigame/bet-accumulator'
      preLoaderRoute: typeof ApiMinigameBetAccumulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/minigame/bet': {
      id: '/api/minigame/bet'
      path: '/api/minigame/bet'
      fullPath: '/api/minigame/bet'
      preLoaderRoute: typeof ApiMinigameBetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/update-result': {
      id: '/api/matches/update-result'
      path: '/api/matches/update-result'
      fullPath: '/api/matches/update-result'
      preLoaderRoute: typeof ApiMatchesUpdateResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/current': {
      id: '/api/matches/current'
      path: '/api/matches/current'
      fullPath: '/api/matches/current'
      preLoaderRoute: typeof ApiMatchesCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/create': {
      id: '/api/matches/create'
      path: '/api/matches/create'
      fullPath: '/api/matches/create'
      preLoaderRoute: typeof ApiMatchesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leagues/standings': {
      id: '/api/leagues/standings'
      path: '/api/leagues/standings'
      fullPath: '/api/leagues/standings'
      preLoaderRoute: typeof ApiLeaguesStandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/reset': {
      id: '/api/game/reset'
      path: '/api/game/reset'
      fullPath: '/api/game/reset'
      preLoaderRoute: typeof ApiGameResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coupons/verify': {
      id: '/api/coupons/verify'
      path: '/api/coupons/verify'
      fullPath: '/api/coupons/verify'
      preLoaderRoute: typeof ApiCouponsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bets/settle': {
      id: '/api/bets/settle'
      path: '/api/bets/settle'
      fullPath: '/api/bets/settle'
      preLoaderRoute: typeof ApiBetsSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bets/active': {
      id: '/api/bets/active'
      path: '/api/bets/active'
      fullPath: '/api/bets/active'
      preLoaderRoute: typeof ApiBetsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/verify': {
      id: '/api/admin/verify'
      path: '/api/admin/verify'
      fullPath: '/api/admin/verify'
      preLoaderRoute: typeof ApiAdminVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/validate-session': {
      id: '/api/admin/validate-session'
      path: '/api/admin/validate-session'
      fullPath: '/api/admin/validate-session'
      preLoaderRoute: typeof ApiAdminValidateSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/api/admin/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBetsRoute: typeof DashboardBetsRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardLeaderboardRoute: typeof DashboardLeaderboardRoute
  DashboardLeagueRoute: typeof DashboardLeagueRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBetsRoute: DashboardBetsRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardLeaderboardRoute: DashboardLeaderboardRoute,
  DashboardLeagueRoute: DashboardLeagueRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AllianceRoute: AllianceRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EntryRoute: EntryRoute,
  OnboardingRoute: OnboardingRoute,
  PlayRoute: PlayRoute,
  SignRoute: SignRoute,
  WelcomeRoute: WelcomeRoute,
  ApiLeaderboardRoute: ApiLeaderboardRoute,
  ApiAdminConfigRoute: ApiAdminConfigRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminValidateSessionRoute: ApiAdminValidateSessionRoute,
  ApiAdminVerifyRoute: ApiAdminVerifyRoute,
  ApiBetsActiveRoute: ApiBetsActiveRoute,
  ApiBetsSettleRoute: ApiBetsSettleRoute,
  ApiCouponsVerifyRoute: ApiCouponsVerifyRoute,
  ApiGameResetRoute: ApiGameResetRoute,
  ApiLeaguesStandingsRoute: ApiLeaguesStandingsRoute,
  ApiMatchesCreateRoute: ApiMatchesCreateRoute,
  ApiMatchesCurrentRoute: ApiMatchesCurrentRoute,
  ApiMatchesUpdateResultRoute: ApiMatchesUpdateResultRoute,
  ApiMinigameBetRoute: ApiMinigameBetRoute,
  ApiMinigameBetAccumulatorRoute: ApiMinigameBetAccumulatorRoute,
  ApiUserCheckInRoute: ApiUserCheckInRoute,
  ApiUserClaimAllianceRewardsRoute: ApiUserClaimAllianceRewardsRoute,
  ApiUserClaimSocialRewardRoute: ApiUserClaimSocialRewardRoute,
  ApiUserClaimWelcomeGiftRoute: ApiUserClaimWelcomeGiftRoute,
  ApiUserClaimWinningsRoute: ApiUserClaimWinningsRoute,
  ApiUserConvertCoinsRoute: ApiUserConvertCoinsRoute,
  ApiUserProfileRoute: ApiUserProfileRoute,
  ApiUserRegisterReferralRoute: ApiUserRegisterReferralRoute,
  ApiUserSubmitQuestVerificationRoute: ApiUserSubmitQuestVerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
